site_name: Compose Modifier Extension

# Repository
repo_name: 'Compose Modifier Extension'
repo_url: 'https://github.com/keygenqt/compose-modifier-ext'

# Navigation
nav:
  - 'Overview': index.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'