site_name: Compose Modifier Extension

# Repository
repo_name: 'Compose Modifier Extension'
repo_url: 'https://github.com/keygenqt/compose-modifier-ext'

# Navigation
nav:
  - 'Overview': index.md
  - 'visible': visible.md
  - 'graphicsCollapse': graphicsCollapse.md
  - 'noRippleClickable': noRippleClickable.md
  - 'interceptionClickable': interceptionClickable.md
  - 'disableVerticalScroll': disableVerticalScroll.md
  - 'disableHorizontalScroll': disableHorizontalScroll.md
  - 'ifFalse': ifFalse.md
  - 'ifTrue': ifTrue.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'